// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tynkhmvywyxffxomfoyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bmtobXZ5d3l4ZmZ4b21mb3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNTg2NjQsImV4cCI6MjA3NzczNDY2NH0.i8sAbYqUbBWO4tFXTzr26nozCXyYSWjL7GDfIbFwuW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});